### ISSUE TITLE
Mod breaks forage

### ISSUE THREAD

**Issue by Killa1214** [ttr/tld-InDoorTemps#1]
Can't forage anything in the game after the mod installed, the crafting needs a minimum temperature of 150. After the installation the temperature was locked at 124 degrees, changing insulation settings won't help with anything.

**Comment by ttr** [comment]
Will check but unlikely as this mod doesn't touch forge /fire functions at all.

On 17 May 2024 21:46:05 GMT+01:00, Killa1214 ***@***.***> wrote:
>Can't forage anything in the game after the mod installed, the crafting needs a minimum temperature of 150. After the installation the temperature was locked at 124 degrees, changing insulation settings won't help with anything.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ttr/tld-InDoorTemps/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ttr** [comment]
Just checked, all works ok.

Just QQ - did You use coal for increasing temp?
Base game will not allow You to rise temp beyond 80C using wood and etc and only coal can do it. When You reach 150C and above You can use wood as normal to keep furnance running.
